export const countries = [
  { name: "Afghanistan", code: "AF", dialCode: "+93" },
  { name: "Bangladesh", code: "BD", dialCode: "+880" },
  { name: "Bhutan", code: "BT", dialCode: "+975" },
  { name: "India", code: "IN", dialCode: "+91" },
  { name: "Nepal", code: "NP", dialCode: "+977" },
  { name: "Pakistan", code: "PK", dialCode: "+92" },
  { name: "Sri Lanka", code: "LK", dialCode: "+94" },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971" },
  { name: "Saudi Arabia", code: "SA", dialCode: "+966" },
  { name: "Qatar", code: "QA", dialCode: "+974" },
  { name: "Kuwait", code: "KW", dialCode: "+965" },
  { name: "Oman", code: "OM", dialCode: "+968" },
  { name: "Bahrain", code: "BH", dialCode: "+973" },
  { name: "Singapore", code: "SG", dialCode: "+65" },
  { name: "Malaysia", code: "MY", dialCode: "+60" },
  { name: "Indonesia", code: "ID", dialCode: "+62" },
  { name: "Thailand", code: "TH", dialCode: "+66" },
  { name: "Philippines", code: "PH", dialCode: "+63" },
  { name: "United Kingdom", code: "GB", dialCode: "+44" },
  { name: "United States", code: "US", dialCode: "+1" },
  { name: "Canada", code: "CA", dialCode: "+1" },
  { name: "Australia", code: "AU", dialCode: "+61" },
];
