export const adminRouteMeta = [
  { path: "dashboard", title: "Dashboard" },
  { path: "users", title: "Users List" },
  { path: "users/:id", title: "User Details" },
  { path: "team/referrals", title: "Referral Tree" },
  { path: "team/autopool", title: "Autopool Manager" },
  { path: "deposits", title: "Deposit Requests" },
  { path: "withdrawals", title: "Withdrawal Requests" },
  { path: "income/logs", title: "Income Logs" },
  { path: "income/rules", title: "Income Rules" },
  { path: "support", title: "Support Tickets" },
  { path: "cms/site", title: "Website CMS" },
  { path: "cms/banners", title: "Banner Manager" },
  { path: "cms/faq", title: "FAQ Manager" },
  { path: "cms/contact", title: "Contact Manager" },
  { path: "settings/general", title: "General Settings" },
  { path: "settings/wallet", title: "Payment Wallet Settings" },
  { path: "settings/security", title: "Security Settings" },
];
