import {
  CircleDollarSign,
  Contact,
  CreditCard,
  FileText,
  LayoutDashboard,
  LifeBuoy,
  Settings,
  Shield,
  UserPlus,
  Users,
  Wallet,
  Workflow,
} from "lucide-react";

export const adminNav = [
  { label: "Dashboard", path: "/admin/dashboard", icon: LayoutDashboard },
  { label: "Users", path: "/admin/users", icon: Users },
  // { label: "Add User", path: "/admin/users/add", icon: UserPlus },
  { label: "Referral Tree", path: "/admin/team/referrals", icon: Workflow },
  { label: "Pool Stats", path: "/admin/autopool/stats", icon: Workflow },
  { label: "Pool Queue", path: "/admin/autopool/queue", icon: Workflow },
  { label: "Pool Tree", path: "/admin/autopool/tree", icon: Workflow },
  { label: "Individual Autopool", path: "/admin/autopool/individual", icon: Workflow },
  { label: "Pool Fund", path: "/admin/autopool/fund", icon: Wallet },
  { label: "Deposits", path: "/admin/deposits", icon: CreditCard },
  { label: "Deposit Settings", path: "/admin/settings/deposit", icon: Settings },
  { label: "Withdrawals", path: "/admin/withdrawals", icon: CircleDollarSign },
  { label: "Wallet Transfers", path: "/admin/wallet-transfers", icon: CreditCard },
  { label: "Income Logs", path: "/admin/income/logs", icon: FileText },
  { label: "Income Rules", path: "/admin/income/rules", icon: FileText },
  { label: "Funds", path: "/admin/funds", icon: Wallet },
  { label: "Support", path: "/admin/support", icon: LifeBuoy },
  { label: "CMS", path: "/admin/cms/site", icon: Contact },
  { label: "Settings", path: "/admin/settings/general", icon: Settings },
  { label: "Security", path: "/admin/settings/security", icon: Shield },
  { label: "Logout", path: "/login", icon: Shield },
];
